export const GlobalAssets = [
  {image: '/images/rendered_image_0.webp', glb: '/glb/rendered_model_0.glb'},
  {image: '/images/rendered_image_1.webp', glb: '/glb/rendered_model_1.glb'},
  {image: '/images/rendered_image_2.webp', glb: '/glb/rendered_model_2.glb'},
  {image: '/images/rendered_image_3.webp', glb: '/glb/rendered_model_3.glb'},
  {image: '/images/rendered_image_4.webp', glb: '/glb/rendered_model_4.glb'},
  {image: '/images/rendered_image_5.webp', glb: '/glb/rendered_model_5.glb'},
  {image: '/images/rendered_image_6.webp', glb: '/glb/rendered_model_6.glb'},
  {image: '/images/rendered_image_7.webp', glb: '/glb/rendered_model_7.glb'},
  {image: '/images/rendered_image_8.webp', glb: '/glb/rendered_model_8.glb'},
  {image: '/images/rendered_image_9.webp', glb: '/glb/rendered_model_9.glb'},  {image: '/images/rendered_image_10.webp', glb: '/glb/rendered_model_10.glb'},
  {image: '/images/rendered_image_11.webp', glb: '/glb/rendered_model_11.glb'},
  {image: '/images/rendered_image_12.webp', glb: '/glb/rendered_model_12.glb'},
  {image: '/images/rendered_image_13.webp', glb: '/glb/rendered_model_13.glb'},
  {image: '/images/rendered_image_14.webp', glb: '/glb/rendered_model_14.glb'},  {image: '/images/rendered_image_15.webp', glb: '/glb/rendered_model_15.glb'},
  {image: '/images/rendered_image_16.webp', glb: '/glb/rendered_model_16.glb'},
  {image: '/images/rendered_image_17.webp', glb: '/glb/rendered_model_17.glb'},
  {image: '/images/rendered_image_18.webp', glb: '/glb/rendered_model_18.glb'},
  {image: '/images/rendered_image_19.webp', glb: '/glb/rendered_model_19.glb'},
];

